# Generated by Django 5.0.3 on 2024-04-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readme_generator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedContent',
        ),
    ]
